### ISSUE TITLE
req.get is not a function

### ISSUE THREAD

**Issue by ktk** [rdf-ext/rdf-body-parser#1]
When using rdf-body-parser with Restify I get an error:    

```
{"code":"InternalError","message":"req.get is not a function"}
```

I guess this is a express function. Would be great if the code does not require this as it is useful outside express use cases as well.

Code: https://github.com/rdf-ext/rdf-body-parser/blob/master/index.js#L30

**Comment by bergos** [comment]
Should be fixed with [latest commit](https://github.com/rdf-ext/rdf-body-parser/commit/ba46381f4ac509c3e230fd5fa0b499fa701c8962)

**Comment by ktk** [comment]
Works thanks
