### ISSUE TITLE
SendGraph should have status code

### ISSUE THREAD

**Issue by nicola** [rdf-ext/rdf-body-parser#5]
look at `send`.

This can do `.send(404)`, `.send(404, "Oh noes")` or just `.send("oh yeah")`

**Comment by bergos** [comment]
In version 4.x of Express it's deprecated to use the combined status code + content `.send` method. It's still very easy to send the status and the content in a single line: `res.status(200).sendGraph(graph)`.

**Comment by nicola** [comment]
well spot, thanks ;)

**Comment by ktk** [comment]
Should I add that to the README for documentation?

**Comment by ktk** [comment]
@bergos and is this Express only or should that work with Restify as well? I use it with Restify so far.

**Comment by bergos** [comment]
I don't think we should add this to the README. It's a feature of the Express/Restify framework. If we don't mention it, we avoid to get out of sync, if something changes.

Restify returns the status code, not the response object. It's a little bit different:

```
res.status(200)
res.sendGraph(graph)
```
